export const territorioCategories = [
  "Todas",
  "Marco general",
  "Matemática",
  "Lengua y Literatura",
  "Ciencias Naturales",
  "Ciencias Sociales",
  "Saberes, Vidas y Mundos",
  "Educación Artística",
  "Educación Tecnológica",
  "Educación Física",
  "Lenguas Extranjeras",
] as const;

export type TerritorioCategory = Exclude<(typeof territorioCategories)[number], "Todas">;

export interface TerritorioEvent {
  id: string;
  dateLabel: string;
  sortDate: string;
  period: string;
  place: string;
  institution?: string;
  category: TerritorioCategory;
  discipline?: "Artes Visuales" | "Música";
  title: string;
  summary: string;
  team: string[];
  photos?: Array<{
    src: string;
    alt: string;
  }>;
  pendingDate?: boolean;
}

export const territorioEvents: TerritorioEvent[] = [
  {
    id: "escuela-lopez-y-planes-musica",
    dateLabel: "1 de julio de 2026",
    sortDate: "2026-07-01",
    period: "Julio 2026",
    place: "Santa Fe",
    institution: "Escuela N.° 5 López y Planes",
    category: "Educación Artística",
    discipline: "Música",
    title: "La enseñanza de Música en la escuela primaria",
    summary: "Observación de clases de Música e intercambio con el equipo directivo sobre la implementación del nuevo Diseño Curricular.",
    team: ["Lía Zilli"],
  },
  {
    id: "san-carlos-artes-visuales",
    dateLabel: "23 de junio de 2026",
    sortDate: "2026-06-23",
    period: "Junio 2026",
    place: "San Carlos Centro",
    category: "Educación Artística",
    discipline: "Artes Visuales",
    title: "Del diseño al aula en Artes Visuales",
    summary: "Presentación de los conceptos estructurantes, los principales enfoques didácticos y la planificación de secuencias.",
    team: ["Rosana Storti"],
  },
  {
    id: "santo-domingo-artes-visuales",
    dateLabel: "10 de junio de 2026",
    sortDate: "2026-06-10",
    period: "Junio 2026",
    place: "Santo Domingo",
    category: "Educación Artística",
    discipline: "Artes Visuales",
    title: "Del diseño al aula en Artes Visuales",
    summary: "Presentación de los conceptos estructurantes, los principales enfoques didácticos y la planificación de secuencias.",
    team: ["Rosana Storti"],
  },
  {
    id: "ism-unl-conversatorio-musica",
    dateLabel: "10 de junio de 2026",
    sortDate: "2026-06-10",
    period: "Junio 2026",
    place: "Santa Fe",
    institution: "Instituto Superior de Música de la UNL",
    category: "Educación Artística",
    discipline: "Música",
    title: "El rol docente en Música desde el nuevo Diseño Curricular",
    summary: "Jornada–conversatorio sobre los aspectos estructurantes del diseño y los aportes para pensar el rol docente.",
    team: ["Lía Zilli"],
  },
  {
    id: "brigadier-lopez-presentacion-general",
    dateLabel: "8 de junio de 2026",
    sortDate: "2026-06-08",
    period: "Junio 2026",
    place: "Santa Fe",
    institution: "Instituto Brigadier López",
    category: "Marco general",
    title: "Presentación general del Diseño Curricular",
    summary: "Proceso de construcción del diseño, selección de contenidos, enfoques transversales y diversificación de la enseñanza, con foco en Lengua y Literatura y Ciencias Sociales.",
    team: ["Verónica Pighin", "Graciela Perussini", "Eliana Bertero", "María Noel Antas", "Rita Kurth", "Flavia Bonadeo"],
    photos: [
      {
        src: "/images/territorio/brigadier-01.jpg",
        alt: "Participantes de la presentación del Diseño Curricular en el Instituto Brigadier López",
      },
      {
        src: "/images/territorio/brigadier-02.jpg",
        alt: "Docentes durante la presentación del Diseño Curricular en el Instituto Brigadier López",
      },
      {
        src: "/images/territorio/brigadier-03.jpg",
        alt: "Equipo expositor de la presentación en el Instituto Brigadier López",
      },
      {
        src: "/images/territorio/brigadier-04.jpg",
        alt: "Panel de la jornada sobre el Diseño Curricular en el Instituto Brigadier López",
      },
    ],
  },
  {
    id: "coronda-artes-visuales",
    dateLabel: "6 de junio de 2026",
    sortDate: "2026-06-06",
    period: "Junio 2026",
    place: "Coronda",
    institution: "Escuela N.° 1244",
    category: "Educación Artística",
    discipline: "Artes Visuales",
    title: "El área Artes Visuales en el nuevo diseño",
    summary: "Recorrido por los conceptos estructurantes, los enfoques didácticos y la planificación de secuencias.",
    team: ["Rosana Storti"],
  },
  {
    id: "aspi-lenguas-extranjeras",
    dateLabel: "6 de junio de 2026",
    sortDate: "2026-06-06",
    period: "Junio 2026",
    place: "Santa Fe",
    institution: "Asociación Santafesina de Profesores de Inglés",
    category: "Lenguas Extranjeras",
    title: "Proyectos didácticos en Lenguas Extranjeras",
    summary: "Presentación del área y abordaje de la planificación de proyectos didácticos en el marco del nuevo diseño.",
    team: ["Farah Schneider", "Silvana Bobbio", "Flavia Bonadeo"],
    photos: [
      {
        src: "/images/territorio/aspi-01.jpg",
        alt: "Docentes trabajando durante el encuentro de Lenguas Extranjeras de ASPI",
      },
      {
        src: "/images/territorio/aspi-02.jpg",
        alt: "Presentación de proyectos didácticos en Lenguas Extranjeras",
      },
      {
        src: "/images/territorio/aspi-03.jpg",
        alt: "Exposición durante el encuentro de la Asociación Santafesina de Profesores de Inglés",
      },
      {
        src: "/images/territorio/aspi-04.jpg",
        alt: "Equipo expositor junto al banner de la Asociación Santafesina de Profesores de Inglés",
      },
    ],
  },
  {
    id: "esperanza-presentacion-general",
    dateLabel: "4 de junio de 2026",
    sortDate: "2026-06-04",
    period: "Junio 2026",
    place: "Esperanza",
    institution: "Escuela Normal N.° 30",
    category: "Marco general",
    title: "El diseño, sus enfoques y la diversificación de la enseñanza",
    summary: "Presentación del proceso de escritura, los conceptos nodales, la propuesta web, los enfoques transversales y Saberes, Vidas y Mundos.",
    team: ["Verónica Pighin", "Fernanda Pagura", "Salomé Márquez", "Flavia Pereyra", "Flavia Bonadeo"],
    photos: [
      {
        src: "/images/territorio/esperanza-01.jpg",
        alt: "Equipo participante de la presentación del Diseño Curricular en Esperanza",
      },
      {
        src: "/images/territorio/esperanza-02.jpg",
        alt: "Integrantes del equipo curricular en la Escuela Normal de Esperanza",
      },
      {
        src: "/images/territorio/esperanza-03.jpg",
        alt: "Exposición sobre el nuevo Diseño Curricular en Esperanza",
      },
      {
        src: "/images/territorio/esperanza-04.jpg",
        alt: "Presentación sobre enfoques y diversificación de la enseñanza en Esperanza",
      },
      {
        src: "/images/territorio/esperanza-05.jpg",
        alt: "Jornada de presentación del Diseño Curricular en la Escuela Normal de Esperanza",
      },
    ],
  },
  {
    id: "ate-casa-espana-musica",
    dateLabel: "2 de junio de 2026",
    sortDate: "2026-06-02",
    period: "Junio 2026",
    place: "Santa Fe",
    institution: "ATE Casa España",
    category: "Educación Artística",
    discipline: "Música",
    title: "Perspectivas para pensar la clase de Música",
    summary: "Encuentro con docentes y equipos directivos sobre los conceptos estructurantes del área y la escritura de clases de Música en la Educación Primaria.",
    team: ["Lía Zilli"],
  },
  {
    id: "mantovani-artes-visuales",
    dateLabel: "2, 5 y 9 de junio de 2026",
    sortDate: "2026-06-02",
    period: "Junio 2026",
    place: "Santa Fe",
    institution: "Escuela Provincial de Artes Visuales Prof. Juan Mantovani",
    category: "Educación Artística",
    discipline: "Artes Visuales",
    title: "Didáctica de las Artes Visuales y Diseño Curricular",
    summary: "Presentación de los conceptos estructurantes y los principales enfoques didácticos del área.",
    team: ["Rosana Storti"],
  },
  {
    id: "artesol-lenguas-extranjeras",
    dateLabel: "29 y 30 de mayo de 2026",
    sortDate: "2026-05-30",
    period: "Mayo 2026",
    place: "Santa Fe",
    institution: "Congreso Internacional ARTESOL · Universidad Católica",
    category: "Lenguas Extranjeras",
    title: "Enseñanza diversificada y aprendizaje basado en proyectos",
    summary: "Dos ponencias sobre aulas heterogéneas, diversificación de la enseñanza y aprendizaje basado en proyectos en Inglés.",
    team: ["Flavia Bonadeo", "Farah Schneider", "Silvana Bobbio", "Natalia Cravero"],
  },
  {
    id: "mateo-booz-matematica",
    dateLabel: "28 de mayo de 2026",
    sortDate: "2026-05-28",
    period: "Mayo 2026",
    place: "Helvecia",
    institution: "ISP N.° 10 Mateo Booz",
    category: "Matemática",
    title: "El área Matemática en el nuevo diseño",
    summary: "Presentación de los conceptos estructurantes y el enfoque didáctico del área, junto con un recorrido por los recursos del Campus Educativo.",
    team: ["María Laura Imvinkelried", "Diego Sequeira", "Cecilia Laspina"],
  },
  {
    id: "ism-unl-didactica-musical",
    dateLabel: "28 de mayo de 2026",
    sortDate: "2026-05-28",
    period: "Mayo 2026",
    place: "Santa Fe",
    institution: "Instituto Superior de Música de la UNL",
    category: "Educación Artística",
    discipline: "Música",
    title: "Didáctica de la Educación Musical en el Nivel Primario",
    summary: "Presentación del área y de las perspectivas musicales para la escritura de una clase en la Educación Primaria.",
    team: ["Lía Zilli"],
  },
  {
    id: "isp8-lenguas-extranjeras",
    dateLabel: "20 de mayo de 2026",
    sortDate: "2026-05-20",
    period: "Mayo 2026",
    place: "Santa Fe",
    institution: "ISP N.° 8 Almirante Brown",
    category: "Lenguas Extranjeras",
    title: "La propuesta plurilingüe del Diseño Curricular",
    summary: "Presentación general del diseño y recorrido por la organización de contenidos y los componentes del área Lenguas Extranjeras.",
    team: ["Silvana Bobbio", "Farah Schneider", "Gisela Greco", "Flavia Bonadeo"],
  },
  {
    id: "venado-tuerto-educacion-fisica",
    dateLabel: "20 de mayo de 2026",
    sortDate: "2026-05-20",
    period: "Mayo 2026",
    place: "Venado Tuerto",
    institution: "Dirección Provincial de Educación Física",
    category: "Educación Física",
    title: "Educar en la diversidad desde Educación Física · Módulo 3",
    summary: "Conversatorio sobre los contenidos de Educación Física propuestos en el diseño y la diversificación curricular.",
    team: ["Silvina Questa", "Silvana Madrid"],
  },
  {
    id: "isp8-profesorado-primaria",
    dateLabel: "21 de abril de 2026",
    sortDate: "2026-04-21",
    period: "Abril 2026",
    place: "Santa Fe",
    institution: "Profesorado de Educación Primaria · ISP N.° 8 Almirante Brown",
    category: "Marco general",
    title: "Enfoques transversales y diversificación de la enseñanza",
    summary: "Presentación del proceso de escritura, los conceptos nodales, la propuesta web y Saberes, Vidas y Mundos.",
    team: ["Fernanda Pagura", "Natalia Cravero", "Flavia Bonadeo"],
  },
  {
    id: "isp8-educacion-especial",
    dateLabel: "30 de abril de 2026",
    sortDate: "2026-04-30",
    period: "Abril 2026",
    place: "Santa Fe",
    institution: "ISP N.° 8 Almirante Brown",
    category: "Marco general",
    title: "Diversificación de la enseñanza y Educación Especial",
    summary: "Presentación dirigida a docentes de los profesorados en discapacidad visual e intelectual y recorrido por los recursos del Campus Educativo.",
    team: ["Marisa Guerra"],
  },
  {
    id: "isef27-plenaria",
    dateLabel: "10 de abril de 2026",
    sortDate: "2026-04-10",
    period: "Abril 2026",
    place: "Santa Fe",
    institution: "ISEF N.° 27 César Vásquez",
    category: "Educación Física",
    title: "El Diseño Curricular en la formación docente de Educación Física",
    summary: "Plenaria sobre el proceso de escritura, los enfoques transversales, la diversificación y la propuesta específica del área.",
    team: ["Silvina Questa", "Silvana Madrid"],
  },
  {
    id: "musica-en-las-escuelas",
    dateLabel: "14 de marzo de 2026",
    sortDate: "2026-03-14",
    period: "Marzo 2026",
    place: "Encuentro virtual",
    institution: "Agrupación Música en las Escuelas",
    category: "Educación Artística",
    discipline: "Música",
    title: "Planificación anual en Música",
    summary: "Taller sobre los conceptos estructurantes del área, la escritura del plan anual y el intercambio a partir de planificaciones de escuelas santafesinas.",
    team: ["Lía Zilli"],
  },
  {
    id: "reconquista-educacion-fisica",
    dateLabel: "5 de noviembre de 2025",
    sortDate: "2025-11-05",
    period: "Noviembre 2025",
    place: "Reconquista",
    institution: "Dirección Provincial de Educación Física",
    category: "Educación Física",
    title: "Educar en la diversidad desde Educación Física · Módulo 2",
    summary: "Conversatorio sobre las prácticas escolares del Diseño Curricular y los abordajes de convivencia desde Educación Física.",
    team: ["Silvina Questa", "Silvana Madrid"],
  },
  {
    id: "santa-fe-educacion-fisica",
    dateLabel: "13 de octubre de 2025",
    sortDate: "2025-10-13",
    period: "Octubre 2025",
    place: "Santa Fe",
    institution: "Dirección Provincial de Educación Física",
    category: "Educación Física",
    title: "Educar en la diversidad desde Educación Física · Módulo 1",
    summary: "Conversatorio sobre el marco general del diseño, la diversidad, la discapacidad y sus abordajes pedagógicos.",
    team: ["Silvina Questa", "Silvana Madrid"],
  },
  {
    id: "supervision-musica",
    dateLabel: "Fecha a confirmar",
    sortDate: "0003-01-01",
    period: "Próximas acciones",
    place: "Provincia de Santa Fe",
    institution: "Jornada con Supervisión de Música",
    category: "Educación Artística",
    discipline: "Música",
    title: "Pensar la clase de Música desde el nuevo diseño",
    summary: "Jornada de trabajo sobre la enseñanza de Música y su abordaje desde el nuevo Diseño Curricular.",
    team: ["Lía Zilli"],
    pendingDate: true,
  },
  {
    id: "san-justo-artes-visuales",
    dateLabel: "Fecha a confirmar",
    sortDate: "0002-01-01",
    period: "Próximas acciones",
    place: "San Justo",
    institution: "Liceo Municipal",
    category: "Educación Artística",
    discipline: "Artes Visuales",
    title: "Del diseño al aula en Artes Visuales",
    summary: "Presentación de los conceptos estructurantes, los enfoques didácticos y la planificación de secuencias.",
    team: ["Rosana Storti"],
    pendingDate: true,
  },
  {
    id: "liceo-santa-fe-artes-visuales",
    dateLabel: "Fecha a confirmar",
    sortDate: "0001-01-01",
    period: "Próximas acciones",
    place: "Santa Fe",
    institution: "Liceo Municipal · Didáctica de las Artes Visuales I y II",
    category: "Educación Artística",
    discipline: "Artes Visuales",
    title: "Planificar la enseñanza en Artes Visuales",
    summary: "Presentación de los conceptos estructurantes, los enfoques didácticos y la planificación de secuencias.",
    team: ["Rosana Storti"],
    pendingDate: true,
  },
  {
    id: "reglamento-centros-educacion-fisica",
    dateLabel: "Sin fecha consignada",
    sortDate: "0000-01-01",
    period: "Otros registros",
    place: "Provincia de Santa Fe",
    institution: "Dirección Provincial de Educación Física · Área Jurídica",
    category: "Educación Física",
    title: "Reglamento para Centros de Educación Física",
    summary: "Participación en la redacción del reglamento para Centros de Educación Física.",
    team: ["Silvina Questa", "Silvana Madrid"],
    pendingDate: true,
  },
];
